version: '3'

services:
  app:
    restart: always
    build: .
    volumes:
      - ./docker/dev_app:/app/dev_app
      - ./docker/dev_project:/app/dev_project
      - ./uw_saml:/app/uw_saml
    environment:
      AUTH: ${AUTH:-SAML_MOCK}
      MOCK_USERNAME: $MOCK_USERNAME
      MOCK_PASSWORD: $MOCK_PASSWORD
      MOCK_EMAIL: $MOCK_EMAIL
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
    stdin_open: true
    tty: true